name: CI Pipeline

on:
    push:
        branches: [dev]
    pull_request:
        branches: [master]

jobs:
    build-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: 24
                registry-url: https://registry.npmjs.org/
                # cache: pnpm
                # cache: "npm"          # enables only if lock file exists

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                version: 10.33.0
            
            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build Package
              run: pnpm run build

            - name: Run Tests
              run: pnpm run test
